POST http://127.0.0.1:8000/api/auth/signup
Content-Type: : application/json

{ "name": "Teste da Silva", "email": "teste@da.silva", "cpf": "08303026119" }

###

GET http://127.0.0.1:8000/api/hello/


{"test": "aoba"}